services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8072:8072"
    container_name: gateway-service
    networks:
      - global-network

networks:
  global-network:
    name: global-network
    external: true
    driver: bridge