server:
  port: ${SPRING_APP_PORT:8072}

spring:
  application:
    name: ${SPRING_APP_NAME:gateway-service}
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: globalCircuitBreaker
            fallbackUri: forward:/fallback
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        failureRateThreshold: 50
        slowCallRateThreshold: 70
        slowCallDurationThreshold: 5000
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
      globalCircuitBreakerConfig:
        slidingWindowSize: 50
        failureRateThreshold: 60
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 4500
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 15000
    instances:
      globalCircuitBreaker:
        baseConfig: globalCircuitBreakerConfig

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls-primary-name: auth-service

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka-naming-server-service:8761/eureka}