apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  namespace: hah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gateway-service-container
          image: europe-west3-docker.pkg.dev/gd-gcp-internship-dc/hah-registry/gateway-service:initial
          ports:
            - containerPort: 8072
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "1Gi"