apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  namespace: hire-a-handyman
spec:
  selector:
    app: gateway-service
  ports:
    - name: gateway
      protocol: TCP
      port: 8072
      targetPort: 8072
  type: LoadBalancer